server:
  port: 8000

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        # Auth Service - Public endpoints (Login, Register, Refresh)
        - id: auth-public
          uri: lb://SWCAMP-AUTH-SERVICE
          predicates:
            - Path=/auth/login, /auth/register, /auth/refresh, /auth/activate
          filters:
            - RewritePath=/auth/(?<segment>.*), /api/v1/auth/${segment}
        
        # Auth Service - Protected endpoints
        - id: auth-protected
          uri: lb://SWCAMP-AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - JwtAuthentication
            - RewritePath=/auth/(?<segment>.*), /api/v1/auth/${segment}
        
        # User Service
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - JwtAuthentication
            - RewritePath=/user/(?<segment>.*), /api/v1/users/${segment}
        
        # Schedule Service
        - id: schedule-service
          uri: lb://SWCAMP-SCHEDULE-SERVICE
          predicates:
            - Path=/schedules/**, /subjects/**
          filters:
            - JwtAuthentication
            - RewritePath=/(?<segment>.*), /api/v1/${segment}
        
        # Enrollment Service
        - id: enrollment-service
          uri: lb://SWCAMP-ENROLLMENT-SERVICE
          predicates:
            - Path=/enrollments/**
          filters:
            - JwtAuthentication
            - RewritePath=/enrollments/(?<segment>.*), /api/v1/enrollments/${segment}
        
        # Course Service
        - id: course-service
          uri: lb://SWCAMP-COURSE-SERVICE
          predicates:
            - Path=/courses/**
          filters:
            - JwtAuthentication
            - RewritePath=/courses/(?<segment>.*), /api/v1/courses/${segment}
        
        # Attendance Service
        - id: attendance-service
          uri: lb://SWCAMP-ATTENDANCE-SERVICE
          predicates:
            - Path=/attendances/**
          filters:
            - JwtAuthentication
            - RewritePath=/attendances/(?<segment>.*), /api/v1/attendances/${segment}
        
        # Reservation Service
        - id: reservation-service
          uri: lb://SWCAMP-RESERVATION-SERVICE
          predicates:
            - Path=/reservations/**
          filters:
            - JwtAuthentication
            - RewritePath=/reservations/(?<segment>.*), /api/v1/reservations/${segment}
