# Development environment sensitive information (Do not upload real secrets to Git)
# Should be ignored by .gitignore: *-dev.yml

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/schoolmate
    username: swcamp
    password: swcamp

jwt:
  secret: your-very-long-secret-key-that-should-be-at-least-256-bits-for-hs256-algorithm-make-sure-this-is-secure-dev-environment
