spring:
  config:
    import: optional:classpath:application-local.yaml
#  datasource:
#    url: jdbc:mariadb://localhost:3306/schoolmate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: swcamp
#    password: swcamp
#    driver-class-name: org.mariadb.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  # type-aliases-package: com.mycompany.project
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: be22ndteam1schoolmateHasToBeVeryLongToSupportHS256AlgorithmSecurityRequirements2026!