spring:
  profiles:
    active: dev

#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  #type-aliases-package: com.mycompany.project
  configuration:
    map-underscore-to-camel-case: true

#spring:
#  datasource:
#    driver-class-name: {driver class}
#    url: jdbc:mariadb://{ip}:{port}/{database}
#    username: {user}
#    password: {password}
#  jpa:


#jwt:
#  secret: {시크릿 키 입력} }
