spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.mycompany.project
  configuration:
    map-underscore-to-camel-case: true

# dev
#spring:
#  datasource:
#    driver-class-name: {driver class}
#    url: jdbc:mariadb://{ip}:{port}/{database}
#    username: {user}
#    password: {password}
#
#jwt:
#  secret: {SecretKey}